- .travis.yml
we want to catch submissions from folks who have not opted to run the
pre-commit hook locally
> have travis run pep8 tests as well

- ipfsApi/client.py
- ipfsApi/commands.py
- test/unit/test_command.py
- test/unit/test_http.py
This is a lot of changes all at once, and I really want a CR.
This ONLY converts all the commands to static methods. We still need to go back and document them all (I want help on that)
> Make Static Methods

- ipfsApi/client.py
- ipfsApi/commands.py
- ipfsApi/http.py
- ipfsApi/utils.py
- test/unit/test_command.py
@BrendanBenshoof what do you think?
> client rework

- ipfsApi/client.py
- ipfsApi/encoding.py
- ipfsApi/filestream.py
- ipfsApi/utils.py
I'm afraid there are still some functions/methods without any docstring I ran out of time to do.
The doctest looking examples are mixture of doctests that would pass if run as doctests (mainly pure functions that don't require setup/a connection) and interactive sessions I pasted/reindented.
It's still rough, but I figure it's better than nothing
> First pass at docstrings with doctest-ish examples

- docs/api_ref.md
- docs/conf.py
- docs/internal_ref.md
- ipfsApi/__init__.py
- ipfsApi/client.py
- ipfsApi/commands.py
- ipfsApi/encoding.py
- ipfsApi/exceptions.py
- ipfsApi/http.py
- ipfsApi/multipart.py
- ipfsApi/utils.py
- test/functional/tests.py
- test/unit/test_encoding.py
- test/unit/test_http.py
- test/unit/test_multipart.py
- test/unit/test_utils.py
- tox.ini
Loosely depends on #63, since it also updates the documentation quite a bit.
> Revamp exception and unicode handling

- README.md
- setup.py
Thanks to this `./setup.py register` now "just works" and will upload the current `README.md` and all information in `setup.py` to PyPI.
Also I fixed some minor issues in the README.
> Add code to `setup.py` to on-the-fly convert the contents of the `README.md` to the ReStructedText required by PyPI

- .travis.yml
- README.md
> Update to test against go-ipfsv0.4.3

- ipfsapi/client.py
- ipfsapi/encoding.py
- ipfsapi/http.py
- test/functional/tests.py
- test/unit/test_encoding.py
- test/unit/test_http.py
Includes some refactoring work to get rid of the "default encoding" thing in `HTTPClient`.
Also includes a minor breaking change in that `c.log_tail()` now returns a generator of dictionaries instead of a list of binary JSON strings.
> Incrementally decode and return stream data sets

- ipfsapi/client.py
- ipfsapi/multipart.py
- test/functional/tests.py
> ENH: Files add accepts unused filename filter

- ipfsapi/encoding.py
CI is erroring out because of this single-line format error.
@alexander255 Go ahead and merge this unless you have a reason not to.
> Fix tox formatting error

- README.md
Previously, the badge was reporting the outcome of the last build, no matter what it was. If the last PR was good, it would say the build was passing, even if master wasn't.
> Switch to show the build status of master

- ipfsapi/version.py
It's been a while since our last release and a few things have accumulated. We probably should do a release at this point, no?
> Release version 0.4.1

- ipfsapi/client.py
> Add a kwarg named 'key' to name_publish

- .coveragerc-py33
- .coveragerc-py36
- .gitignore
- .travis.yml
- README.md
- ipfsapi/client.py
- setup.py
- test-requirements.txt
- test.sh
- test/functional/tests.py
- tox.ini
Need to check if shutdown test correctly interactions with the CI
> IPFS v0.4.10

- .travis.yml
- ipfsapi/client.py
- test/functional/tests.py
Fixes the CI issues seen in #123.
> Update CI to go-IPFS v0.4.14

- ipfshttpclient/multipart.py
- ipfshttpclient/utils.py
- requirements-codestyle.txt
- test/unit/test_multipart.py
- test/unit/test_utils.py
- tox.ini
Follow-up of #145, onto different branch.
> Rewrite `ipfsapi/multipart.py` to address the issues mentioned in #104

- .gitignore
- .travis.yml
- requirements-codestyle.txt
- test/combine-coverage.py
- test/run-tests.py
- tox.ini
Add testing on macOS and much improved test coverage data collection (which previously was broken)
> Improve testing

- ipfshttpclient/client/key.py
- ipfshttpclient/client/name.py
See: https://github.com/ipfs/go-ipfs/pull/5979
> Improve documentation on ttl option

- ipfshttpclient/client/pin.py
- test/functional/test_pin.py
A must have for using pin.ls on large repositories.
> pin: add optional paths arg to ls

- CHANGELOG.md
- README.md
- ipfshttpclient/client/base.py
- ipfshttpclient/client/bootstrap.py
- ipfshttpclient/client/swarm.py
- ipfshttpclient/exceptions.py
Change all references of 'MultiAddr' to 'Multiaddr'.
> Fixes #198

- README.md
- ipfshttpclient/client/base.py
- ipfshttpclient/http.py
- ipfshttpclient/utils.py
- test/unit/test_http.py
Supersedes  and closes #155.
Fixes #154.
> Add username + password HTTP basic authentication support

- ipfshttpclient/client/files.py
- test/functional/test_files.py
> Added cid_version parameter support for client.add

- test/unit/test_filescanner.py
- tox.ini
> Remove dependency on mock; upgrade mypy and pytest

- README.md
- test/functional/conftest.py
- test/functional/test_pin.py
Don't rely on current working folder.
> test_pin.py - use pytest fixture to find test input folder

- ipfshttpclient/exceptions.py
- ipfshttpclient/filescanner.py
- test/unit/test_exceptions.py
- test/unit/test_filescanner.py
> Move MatcherSpecInvalidError
