- ipfsApi/client.py
Assuming that I am trying to use name_resolve correctly:
>>> api.name_resolve('QmXfrS3pHerg44zzK6QKQj6JDk8H6cMtQS7pdXbohwNQfK')
It looks as if it needs to be specified as an `ArgCommand`, rather than
as a `Command`.
> name_resolve should be an ArgCommand, not a Command

- ipfsApi/client.py
This permits the caller to request the default value explicitly
by pasing None to either host, port, or base when instantiating
ipfsApi.client.Client.
Closes #7
> use defaults when host, port, or base == None

- ipfsApi/exceptions.py
- ipfsApi/http.py
This causes `ipfsApi.http.HTTPClient` to raise an exception in response to
HTTP errors, rather than successfully returning an error message to the
caller.  This makes it easier to differentiate errors from successful
responses.
Closes #13.
> raise ipfsApiError on http errors

- .gitignore
- ipfsApi/utils.py
- requirements.txt
- setup.cfg
- test/tests.py
- tox.ini
This pull request
- Adds docstrings with docstrings to ipfsApi.utils
- Adds py.test as the test runner
- Adds Tox configuration
- Fixes the IpfsApiTest under Python 2.6
To run the test suite
```
ipfs daemon &
pip install tox
tox
```
> Add doctests for utils, and tox support

- ipfsApi/client.py
This addresses the discussion in #11 by replacing `__client__` with
`_clientfactory`, since that's what it does.
> avoid having both __client__ and _client in the same class

- ipfsApi/client.py
- ipfsApi/commands.py
- ipfsApi/encoding.py
- ipfsApi/exceptions.py
- ipfsApi/filestream.py
- ipfsApi/http.py
- ipfsApi/utils.py
- requirements.txt
- setup.py
- test-requirements.txt
- tools/pre-commit
- tox.ini
417bf08 (Lars Kellogg-Stedman, 3 minutes ago)
fix all pep8 errors
this commits corrects all the pep8 errors reported by flake8 with the
following exceptions:
- we ignore everything in test/, because there are a number of
problems there right now.
- we explicitly disable checks E222 and E221 (too much whitespace
before/after operators), because we're doing fancy alignment of
multiple assignments in several of the source files
- we explicitly disable check F403 (`from something import *`), because
we use that construct on purpiose.
abd8880 (Lars Kellogg-Stedman, 5 minutes ago)
add support for pep8 tests in tox config
this commit configures tox to run [pep8][] tests.  It also moves
test-related requirements (like `pytest`) into the file
`test-requirements.txt`, which means they won't be …
> Add pep8 tests to tox configuration

- LICENSE.txt
- README.rst
this commit updates the 'how to contribute' section of README.rst, and
also includes a copy of the MIT license (because `setup.py` indicates
that this is the license under which this module is distributed).
> updates to readme + licensing information

- ipfsApi/http.py
It's best to use SSL when pulling from a gateway, but the way this was written originally didn't allow for that. This is a backwards-compatible way to add support for that use case.
> Add support for specifying HTTPS or HTTP in the hostname.

- ipfsApi/http.py
Check for `stream=True` option for requests and just return the raw stream.
Useful for `cat`, especially when retrieving non-text data
eg:
```
r = api.cat('<hash>', stream=True)
data = r.read()
```
> support streaming for /cat option with stream=True

- ipfsApi/encoding.py
- test/unit/test_encoding.py
This fixes the JSON decoder to handle chained responses which have newlines between the objects, such as for `api.ping(...)`.
> Fix for chained responses with newlines

- ipfsApi/utils.py
- test/functional/tests.py
* Fixed encoding issue in parse_pyobject by decoding it as latin_1. This might relate to IPFS Bug #1817 https://github.com/ipfs/go-ipfs/issues/1817 
* Added  test for get_pyobject() and add_pyobject() in test/functional/tests.py which works fine.
NB: Other tests in tests.py fail, there might be an issue with the multipart code. At the moment test/functional/tests.py is not evaluated by tox because setup.cfg limits tests to tests/unit.
> Fix for get_pyobject() and add_pyobject() failing

- .travis.yml
- README.md
- ipfsApi/client.py
- test/functional/tests.py
TravisCI previously ignored the functional tests that required an IPFS daemon to be running. #46 enabled those tests, but did not configure TravisCI to run an IPFS daemon. Now, Travis will download the release version of go-ipfs v0.4.3rc2 and run it before running the tests, ensuring that the functional tests pass too.
There have been some changes to the HTTP API responses since go-ipfs v0.4.3rc1, so this PR also updates the tests to reflect those changes.
This will resolve #50
> Fix TravisCI and make compatible with go-ipfs v0.4.3rc2

- test/unit/test_utils.py
Apparently it was mostly luck that this has worked for some time.
> Fix unit test `test.unit.test_utils.TestUtils.test_ls_dir` to not rely on the ordering of files on the file system

- .travis.yml
Since there's a new release candidate, the old build errors while trying to fetch release candidate 2.
> Update to build against go-ipfs v0.4.3-rc3

- test/functional/tests.py
> Make unit tests fail with a descriptive error message if local `ipfs daemon` node is not running

- ipfsApi/client.py
- test/functional/tests.py
Adding bitswap command as suggested by #42.
Closing #47.
> Add bitswap commands

- ipfsApi/client.py
- test/functional/tests.py
Use appropriate default parameters here.
> Clean up the API client constructor and default params

- ipfsapi/client.py
Useful for creating new keys in order to push multiple objects to the IPNS namespace using name_publish.
> added key_gen function to client

- README.md
Just found this rotting in our branch list for some reason. It still makes sense to document this (better late than never) I guess.
> Add information about `.connect()` to `ipfsApi 0.2.x` upgrade section

- docs/releasing.md
A quick run-down on what happens when I create a new release, so that something like #90 can be done by other people as well, if I should not be around anymore for any reason.
(Note that my workflow for pushing documentation to the server is actually somewhat different from what is documented here, but it's just convenience and will like soon change again if `ipfs-cluster` turns out to be useful.)
> Add documentation about releasing new versions

- ipfsapi/client.py
The current Python API call for IPNS name resolution (name_resolve) does not support the recursive and nocache options that are supported on the command line; this very minimal pull request adds them, with their defaults set to false (as on the command line) so that existing Python code that relies upon the current API will work without modification.
> Add recursive and nocache options to name_resolve API call.

- ipfsapi/encoding.py
- test/functional/tests.py
- test/unit/test_encoding.py
Currently the `add_json` method doesn't sort keys before serializing a Python object to JSON.
Example script:
```
import ipfsapi
import json
from pprint import pprint
api = ipfsapi.connect('127.0.0.1', 5001)
data = """{
"Action": 0,
"Type": 0,
"Name": "hiya",
"PubKey": "tprv8ZgxMBicQKsPd1Cv3T..."
}"""
print(data)
data = json.loads(data)
ipfs_object_hash = api.add_json(data)
print("ipfs_object_hash: %s" % ipfs_object_hash)
```
Script on node1:
```
$ ./venv/bin/python t1.py
{
"Action": 0,
"Type": 0,
"Name": "hiya",
"PubKey": "tprv8ZgxMBicQKsPd1Cv3T..."
}
ipfs_object_hash: QmarCcvguM1tsyxboHKtRD8J3RA9446HKg2TnLPhevMiQd
```
Same script on node2:
```
$ ./venv/bin/python t1.py
{
"Action": 0,
"Type": 0,
"Name": "hiya",
"PubKey": "tprv8ZgxMBicQKsPd1Cv3T..."
}
ipfs_object_hash: …
```
> sort keys when serializing objects to JSON

- ipfsapi/client.py
- test/functional/tests.py
This also refactors `IpfsApiTest` to use py.test `assert` and to properly clean
up pins after each test.
Fixes #84.
> Add support and tests for several `.add()` options

- docs/releasing.md
- ipfsapi/version.py
“Restore feature-parity with go-IPFS 0.4.10”
> Release version 0.4.2

- README.md
- tools/pre-commit
There's no `pep8` environment configured in `tox.ini`.
We should use `codestyle` instead.
> Fix pre-commit script

- ipfsapi/client.py
- ipfsapi/http.py
- test/functional/tests.py
It's useful to get one block of a file, such as using libmagic to determine the file type.
> add 'offset' and 'length' parameters to cat method

- ipfsapi/multipart.py
When add a directory in Windows System,the result always return with ```QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn```.
Because the dir separator using '\\' in Windows but needed is '/'.
I fix this bug for Python's ipfs api.
> Fix a Bug While Upload directories in Windows

- docs/api_ref.md
The inline code was initially marked with a single back tick.  
The recommended way is with double back-ticks.  
I checked locally. Sphinx generated the proper HTML code, including the missing words.
> Fixed Issue 136 (Missing Word in Documentation)

- ipfsapi/multipart.py
- ipfsapi/utils.py
- requirements-codestyle.txt
- test/unit/test_multipart.py
- test/unit/test_utils.py
- tox.ini
Fixes #104 and some other stuff. Also gets rid of `requests` in the multipart code making it framework agnostic again, while probably being more efficient, but definitely more resource aware:
* Even when streaming large directory trees the maximum number of open fds should only be `tree_depth + 1` (one fd for each directory layer and one for the actual file in question)
* Files are streamed from disk using generators so there should never be more than a couple of kilobytes of file data be present in RAM
> Rewrite `ipfsapi/multipart.py` to address the issues mentioned in #104

- docs/conf.py
- docs/http_client_ref.md
- ipfshttpclient/client/base.py
- ipfshttpclient/client/block.py
- ipfshttpclient/client/files.py
- ipfshttpclient/client/key.py
- ipfshttpclient/client/miscellaneous.py
- ipfshttpclient/client/name.py
- ipfshttpclient/client/object.py
- ipfshttpclient/client/pin.py
- ipfshttpclient/client/unstable.py
- ipfshttpclient/encoding.py
- ipfshttpclient/http.py
- ipfshttpclient/multipart.py
- ipfshttpclient/utils.py
The new [hierarchical `Client` class](https://github.com/ipfs/py-ipfs-api/commit/6a3827c4b73ddbbb8a156e1aab89918a950ceb2c) is something that the Sphinx autodoc simply does not understand. To remedy this PR adds a new plugin to our Sphinx configuration file that will automatically detect the relevant property objects and render them as sub-class in the output.
Additionally some miscellaneous miscellaneous documentation fixes were applied in several places.
TODO: Investigate whether [`Sphinx.add_autodoc_attrgetter`](http://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx.application.Sphinx.add_autodoc_attrgetter) can be used to simplify and future-proof the plugin.
> Update documentation generator for new hierachical `Client` class

- ipfshttpclient/exceptions.py
- ipfshttpclient/http.py
- test/unit/test_http.py
Due to technical reasons (a frame format is required) this will only work with daemon JSON responses, not raw byte streams.
Related: #133.
> Raise exceptions for daemon errors that occured after some messages have already been sent to the client

- ipfshttpclient/client/__init__.py
- ipfshttpclient/client/base.py
- ipfshttpclient/client/bitswap.py
- ipfshttpclient/client/block.py
- ipfshttpclient/client/bootstrap.py
- ipfshttpclient/client/config.py
- ipfshttpclient/client/dht.py
- ipfshttpclient/client/files.py
- ipfshttpclient/client/key.py
- ipfshttpclient/client/miscellaneous.py
- ipfshttpclient/client/name.py
- ipfshttpclient/client/object.py
- ipfshttpclient/client/pin.py
- ipfshttpclient/client/pubsub.py
- ipfshttpclient/client/repo.py
- ipfshttpclient/client/swarm.py
- ipfshttpclient/client/unstable.py
- ipfshttpclient/encoding.py
- ipfshttpclient/http.py
- ipfshttpclient/multipart.py
- requirements-codestyle.txt
- test/functional/test_files.py
- test/unit/test_http.py
- tox.ini
Previously the code would rely on a heuristic where it would return only a single item if the daemon only returned one item, a list otherwise. This could have unexpected results in some cases (#133).
`.add()` is a special case, as it will only return a single item if a single *regular file* (but not directory) was added. It's parameter list was also changed so that adding several items now means passing several positional parameters, instead of a single parameter containing a list.
Along with #166 this closes #133
> Make it part of the function declaration whether the given function returns only a single item or not

- ipfshttpclient/client/files.py
- ipfshttpclient/multipart.py
- test/functional/test_files.py
- test/run-tests.py
- test/unit/test_multipart.py
nocopy is accessible form the CLI, so let's make it accessible from API as well.
> client: add support for nocopy, raw-leaves to add method

- docs/http_client_ref.md
- ipfshttpclient/http.py
- requirements-testing.txt
- test/functional/test_block.py
- test/unit/test_encoding.py
- test/unit/test_http.py
- test/unit/test_utils.py
Follow-up of #169 using `pytest-localserver` instead of `httmock` for testing.
> Add timeout option

- ipfshttpclient/client/name.py
- test/functional/conftest.py
- test/functional/test_name.py
Tests take a long time to run. Would be nice if daemon supported offline mode; or at least support local resolve to resolve own keys instantly.
> name tests and DHT-related arguments for publish

- ipfsapi/encoding.py
Python encodes ASCII by default and escapes the unicode characters.
This fix enforces utf-8.
```
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ipfsapi
>>> api = ipfsapi.connect('127.0.0.1', 5001)
>>> val = {"key": "Value, não é?"}
>>> api.add_json(val)
'QmNRzhk1e4cHYpqej7LjguBd5fP4uLyVYTQFfJFGm9ESLQ'
>>> api.get_json('QmNRzhk1e4cHYpqej7LjguBd5fP4uLyVYTQFfJFGm9ESLQ')
{'key': 'Value, não é?'}
>>> 
```
This is ok, expected behavior.
https://ipfs.io/ipfs/QmNRzhk1e4cHYpqej7LjguBd5fP4uLyVYTQFfJFGm9ESLQ <-- Ok here as well.
> Fixes inconsistent encoding behavior.

- ipfshttpclient/client/files.py
- test/functional/test_files.py
Fixes assert failure introduced in 52df768c.
Added test that would have caught the problem.
```
AssertionError: Called IPFS HTTP-Client function should only ever return a list, when not streaming a response
```
> files.cp: fix return attribute in cp to be void

- ipfshttpclient/http.py
- test/functional/conftest.py
- test/functional/test_name.py
- test/functional/test_unstable.py
My earlier prayer has been answered incredibly fast: go-ipfs 0.4.19 added an offline flag. Oh if only I had this yesterday... would have saved me hours. Now name tests run within a few seconds instead of tens of minutes!
I also tried launching the whole daemon with `--offline` but the bitswap and pubsub tests require online mode. Regardless of testing, though, the API should support offline at the granularity of connection and request, which this PR adds.
f96aaee is not strictly necessary, but it fixes the test hang when run with `--offline` daemon.
d43208d is unrelated. I just noticed the kwargs in the docs, but it was not in the code. It looked harmless and useful to add it, but if not, I can remove this commit from this PR.
> Offline mode

- README.md
- ipfshttpclient/http.py
- ipfshttpclient/requests_wrapper.py
- ipfshttpclient/version.py
- renaming_status.txt
Fixes #184, details from commit message:
> Fix issues in the requests wrapper with `urllib3` 1.21.* and 1.25.*
>
> For older `urllib3` versions an attribute we assumed to be present was not,
causing a crash.
> 
> For the latest version inheriting our patched `HTTPSConnectionPool` class from
the wrong base class `urllib3.HTTPConnectionPool` (rather than
`urllib3.HTTPSConnectionPool`) caused HTTPS validation to mysteriously fail,
as the system CA store wasn't loaded anymore.
Additionally it includes a new environment variable that can be used to temporarily disable loading of the requests wrapper/patcher.
> Fix `urllib3`'s loading of the system CA bundle on 1.25+

- README.md
The example states "client.pin_ls(...", but the correct form seems to be "client.pin.ls(..."
> typo in README.md regarding client.pin.ls example?

- CHANGELOG.md
- README.md
- ipfshttpclient/http_common.py
- ipfshttpclient/http_httpx.py
- ipfshttpclient/http_requests.py
- ipfshttpclient/requests_wrapper.py
- test/unit/test_http.py
- test/unit/test_http_httpx.py
- tox.ini
Implements #197 for both HTTPx and requests (and this may well be the last time I do something for that “backend” – can't wait to do the switch in 0.7.x).
> Add support for connecting to the IPFS daemon over Unix domain sockets

- ipfshttpclient/client/dag.py
I am not sure if I did this correctly. I still do not understand some parts of the code. There are lots of backawards compatibility stuff that I do not know (yet).
> Added optional arguments to `/dag/put`

- .gitignore
- ipfshttpclient/encoding.py
- ipfshttpclient/filescanner.py
- test/functional/test_files.py
- test/run-tests.py
- tox.ini
1. Fix httpcore dependency by removing comment that broke pip
2. Add scripts to run tests and typing checks with Docker against multiple versions of Python
Previous to this change, attempts to run
tox -e styleck -e typeck
..resulted in this error:
ERROR: Invalid requirement: 'httpcore (~= 0.10.2)  # Has Unix domain socket support'
The error is caused by this part of that line being present in `tox.ini`:
This commit does not fix the typing errors referenced in #255 but does demonstrate the typing errors now that the `httpcore` dependency is fixed.
> Fix httpcore dependency; fix style linting

- ipfshttpclient/client/__init__.py
- ipfshttpclient/client/base.py
Source of these warnings should be corrected when the sources of the other suppressed warnings in the code base are fixed.
This change is likely to make the build green, which will aid in future refactoring and warning corrections.
> Suppress return type warnings in base.py so build will be green

- .travis.yml
- ipfshttpclient/client/base.py
- ipfshttpclient/exceptions.py
- ipfshttpclient/filescanner.py
- ipfshttpclient/http_common.py
- ipfshttpclient/multipart.py
- ipfshttpclient/utils.py
- pyproject.toml
- test/functional/test_files.py
- test/unit/test_encoding.py
- test/unit/test_multipart.py
- tox.ini
Reduction in scope of #260, since this client is pledged to support Python 3.6 thru its EOL.
#261 should be merged before this PR is.
> Bump min Python version from 3.5.4 to 3.6.2

- ipfshttpclient/client/__init__.py
- ipfshttpclient/exceptions.py
- test/functional/conftest.py
- test/unit/test_client.py
Closes #253 by addressing the issue found during code review.
Once this is merged, I think we can finally release py-ipfs-http-client 0.8!
> Update of „Change exceptions.VersionMismatch into warning“

- test/functional/conftest.py
- test/functional/test_other.py
Inspired by #224 and the aggravation of the recent transient build failures connecting to the docker daemon, though that is a separate issue. It felt the same :@
* Print exception (on a double new line due to progress percentages)
* Refactor to use pytest fixtures instead of an evil evil `global` variable
* Remove some comments that restate `pytest` documentation about `fixture` scopes
> Print exception thrown while trying to connect to IPFS 

- pyproject.toml
- tools/verify/Dockerfile
- tools/verify/entrypoint.sh
- tools/verify/validate.sh
- verify.sh
Carved out of https://github.com/ipfs-shipyard/py-ipfs-http-client/pull/257
Adds scripts that use Docker to verify the library's compatibility with the versions of Python it supports.
With this change, the `travis` build will still fail with style linting and type linting errors. Change #257 will correct the style linting errors, and this change will be rebased once that one is merged.
Once #257 and this change are both merged, the scripts in this change will fail on the first Python version, `3.5.4`, because the current code base has syntax at https://github.com/ipfs-shipyard/py-ipfs-http-client/blob/52c1d2a28a43fb020d4d6375be2b8d432267c37d/ipfshttpclient/http_httpx.py#L48 that is not supported by `3.5.4` - this problem will be corrected by #258.
> Add scripts to verify compatibility with multiple Python versions

- CHANGELOG.md
- ipfshttpclient/version.py
- test/run-tests.py
- tox.ini
* Change version marker from 0.7.0 to 0.8.0a1
* Fix spelling and grammar in change log
* Remove polyfill for `contextlib.suppress` (not needed since Python 3.4)
* Fix 'custom marker not registered' warning related to `pytest.mark.last` (provided by `pytest-ordering` module)
@ntninja I see the project in my PyPi account but it doesn't look like I have any elevated privileges on it.
What are next steps?
> Prep to release 0.8.0a1

- test/functional/test_miscellaneous.py
- test/run-tests.py
- tox.ini
pytest_ordering seems unmaintained as it hasn't been updated in two years: https://github.com/ftobia/pytest-ordering. It is also broken, at least in Nixpkgs: https://github.com/NixOS/nixpkgs/pull/122264.
pytest_order is a maintained and working fork.
I added a similar patch to Nixpkgs a while ago to make it work there: https://github.com/NixOS/nixpkgs/blob/6965eef223f491cc1d9289ce972d8ab6811a2d28/pkgs/development/python-modules/ipfshttpclient/default.nix#L59-L63. It would be nice to get rid of this patch for a future version.
I bumped the version in tox.ini a little since version 0.6 does not appear in https://pypi.org/project/pytest-order/#history.
I'm not sure if the line with `markers =` in tox.ini is still correct with this change, please check.
> Replace pytest_ordering with pytest_order
